name: Build and Deploy Personal Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Registry
      uses: docker/login-action@v1
      with:
        username: nologin
        password: ${{ secrets.API_KEY }}
        registry: ${{ secrets.REGISTRY_ENDPOINT }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_ENDPOINT }}/portfolio:${{ github.sha }} .
        docker tag ${{ secrets.REGISTRY_ENDPOINT }}/portfolio:${{ github.sha }} ${{ secrets.REGISTRY_ENDPOINT }}/portfolio:latest
        docker push ${{ secrets.REGISTRY_ENDPOINT }}/portfolio:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_ENDPOINT }}/portfolio:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          docker login -u nologin -p ${{ secrets.API_KEY }} ${{ secrets.REGISTRY_ENDPOINT }}
          docker pull ${{ secrets.REGISTRY_ENDPOINT }}/portfolio:latest
          docker stop portfolio || true
          docker rm portfolio || true
          docker run -d --name portfolio --network host ${{ secrets.REGISTRY_ENDPOINT }}/portfolio:latest
